=== AlexandreLamb/TPWeb/TP 1/listeBouteille.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT listeBouteille (bouteille)+>
        <!ATTLIST listeBouteille
                xmlns CDATA #FIXED ''>

        <!ELEMENT bouteille (marque,composition,provenance,codeBarre,ph,
                contenance)>
        <!ATTLIST bouteille
                xmlns CDATA #FIXED ''>

        <!ELEMENT marque (#PCDATA)>
        <!ATTLIST marque
                xmlns CDATA #FIXED ''>

        <!ELEMENT composition (ion)+>
        <!ATTLIST composition
                xmlns CDATA #FIXED ''>

        <!ELEMENT provenance (Source,departement)>
        <!ATTLIST provenance
                xmlns CDATA #FIXED ''>

        <!ELEMENT codeBarre (#PCDATA)>
        <!ATTLIST codeBarre
                xmlns CDATA #FIXED ''>

        <!ELEMENT ph (#PCDATA)>
        <!ATTLIST ph
                xmlns CDATA #FIXED ''>

        <!ELEMENT contenance (#PCDATA)>
        <!ATTLIST contenance
                xmlns CDATA #FIXED ''>

        <!ELEMENT ion (#PCDATA)>
        <!ATTLIST ion
                xmlns CDATA #FIXED ''
                type NMTOKEN #REQUIRED>

        <!ELEMENT Source (#PCDATA)>
        <!ATTLIST Source
                xmlns CDATA #FIXED ''>

        <!ELEMENT departement (#PCDATA)>
        <!ATTLIST departement
                xmlns CDATA #FIXED ''>

=== AlexandreLamb/TPWeb/TP 1/listeBouteille.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listeBouteille SYSTEM "listeBouteille.dtd">
<listeBouteille>
    <bouteille>
        <marque>Cristaline</marque>
            <composition>
                <ion type="positifs">calcium</ion>
                <ion type="positifs">magnesium</ion>
                <ion type="negatif">chlorure</ion>
                <ion type="positifs">nitrate</ion>
            </composition>
        <provenance>
            <Source>St Cyr</Source>
            <departement>Loiret</departement>
        </provenance>
        <codeBarre>3274080005003</codeBarre>
        <ph>7,45</ph>
        <contenance>150cl</contenance>
    </bouteille>

    <bouteille>
        <marque>Cristaline</marque>
        <composition>
            <ion type="positifs">calcium</ion>
            <ion type="positifs">magnesium</ion>
            <ion type="negatif">chlorure</ion>
            <ion type="positifs">nitrate</ion>
        </composition>
        <provenance>
            <Source>Aur√®le</Source>
            <departement>Alpes martimes</departement>
        </provenance>
        <codeBarre>3268840001008</codeBarre>
        <ph>7,4</ph>
        <contenance>50cl</contenance>
    </bouteille>

    <bouteille>
        <marque>Volvic</marque>
        <composition>
            <ion type="positifs">calcium</ion>
            <ion type="positifs">magnesium</ion>
            <ion type="negatif">chlorure</ion>
            <ion type="positifs">nitrate</ion>
        </composition>
        <provenance>
            <Source>Volvic</Source>
            <departement>Loiret</departement>
        </provenance>
        <codeBarre>3057640117008</codeBarre>
        <ph>7</ph>
        <contenance>150cl</contenance>
    </bouteille>

</listeBouteille>
